config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :places
  resources :countries

end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :places, :dependent => :destroy

  validates :name, :presence => true,
                   :length => { :maximum => 30 }
end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :country

  validates :postal_code, :presence => true,
                          :length => { :maximum => 5 }
  validates :name, :presence => true,
                   :length => { :maximum => 50 }

  def self.search(search_params)
    where("name ILIKE ?", "%#{search_params}%") ||
    where("postal_code ILIKE ?", "%#{search_params}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    if params[:search].present?
      @countries = Country.where("name LIKE ?", "%#{params[:search]}%")
    else
      @countries = Country.all
    end

    @country = Country.new
    @add_mode = params[:add]
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to countries_path, notice: 'Country was successfully created.' }
        format.json { render :index, status: :created, location: @country }
      else
        @countries = Country.all
        @add_mode = true
        format.html { render :index }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    if params[:search].present?
      @places = Place.search(params[:search])
    else
      @places = Place.all
    end

    @place = Place.new
    @add_mode = params[:add]
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to places_path, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        @places = Place.all
        @add_mode = true
        format.html { render :index }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:postal_code, :name, :country_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/countries/_form.html.erb
<%= form_for @country, :html => { :class => "form-horizontal country" } do |f| %>

  <% if @country.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @country.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                countries_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/countries/edit.html.erb
<%- model_class = Country -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/countries/index.html.erb
<%- model_class = Country -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= link_to "Add", countries_path(:add => true), :method => :get, :class => "btn btn-primary" %>
</br>
</br>

<%= form_tag(countries_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search", :class => "form-control" %>
  </br>
  <%= submit_tag "Search", :class => "btn btn-secondary" %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= link_to country.id, country_path(country) %></td>
        <td><%= country.name %></td>
        <td><%=l country.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_country_path(country), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      country_path(country),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="col-lg-4">
  <% if @add_mode %>
    <%= render :partial => 'form' %>
  <% end %>
</div>

<div class="col-lg-4"></div>

<div class="col-lg-4">
  <%= link_to "Next",
              places_path,
              :class => 'btn btn-primary' %>
</div>

app/views/countries/new.html.erb
<%- model_class = Country -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/countries/show.html.erb
<%- model_class = Country -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @country.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              countries_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_country_path(@country), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              country_path(@country),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PoslovnaCheckpoint</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= nav_bar static: :top, :responsive => true do %>
  <%= menu_group :pull => :left do %>
    <%= menu_item "Home", root_path %>
    <%= menu_item "Countries", countries_path %>
    <%= menu_item "Places", places_path %>
  <% end %>
<% end %>

<div class="container">

  <%= yield %>

</div>

</body>
</html>

app/views/places/_form.html.erb
<%= form_for @place, :html => { :class => "form-horizontal place" } do |f| %>

  <% if @place.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @place.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :postal_code, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :postal_code, :class => 'form-control' %>
    </div>
    <%=f.error_span(:postal_code) %>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :country_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_select(:country_id,
                              Country.all,
                              :id,
                              :name,
                              {},
                              { :class => "form-control" }) %>
    </div>
    <%=f.error_span(:country_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                places_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/places/edit.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/places/index.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= link_to "Add", places_path(:add => true), :method => :get, :class => "btn btn-primary" %>
</br>
</br>

<%= form_tag(places_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search", :class => "form-control" %>
  </br>
  <%= submit_tag "Search", :class => "btn btn-secondary" %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:postal_code) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:country_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= link_to place.id, place_path(place) %></td>
        <td><%= place.postal_code %></td>
        <td><%= place.name %></td>
        <td><%= place.country.name %></td>
        <td><%=l place.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_place_path(place), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      place_path(place),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="col-lg-4">
  <% if @add_mode %>
    <%= render :partial => 'form' %>
  <% end %>
</div>

<div class="col-lg-4"></div>
<div class="col-lg-4">
  <%= link_to "Previous",
              countries_path,
              :class => 'btn btn-primary' %>
</div>

app/views/places/new.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/places/show.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:postal_code) %>:</strong></dt>
  <dd><%= @place.postal_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @place.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country_id) %>:</strong></dt>
  <dd><%= @place.country_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              places_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_place_path(@place), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              place_path(@place),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>